### ISSUE TITLE
Dataset sample

### ISSUE THREAD

**Issue by lmw0320** [bharatsubedi/OCR-Text-detection-and-Recognition-#1]
Could you pls show the sample of dataset for training？
I want to train models for chinese characters,  and the detail of dataset I need to know...Thanks in advance.

**Comment by bharatsubedi** [comment]
@lmw0320 dataset format is similar to the ICDAR data format. you can check folder structure inside the utils/config.py file. I train the network using grayscale images and character by character detection, not a string. If you need more help let me know.

**Comment by lmw0320** [comment]
> @lmw0320 dataset format is similar to the ICDAR data format. you can check folder structure inside the utils/config.py file. I train the network using grayscale images and character by character detection, not a string. If you need more help let me know.

Thanks for your reply. I also want to know whether the model is suitable for the characters in circle shape such as stamp..

**Comment by bharatsubedi** [comment]
It will work for circle shape also, it depends on your training data.

**Comment by lmw0320** [comment]
> It will work for circle shape also, it depends on your training data.

As I check some blogs describing for this FOTS, it seems the recgnition model to be similar as CRNN, so if the data is circle shape, it shoule be treated to horizontal shape during RoIRotate stage, is it right?  
And,  during RoIRotate stage,  the output data from detecting model would be treated by affine transformation, not  polar coordinates transformation.  I'm not clear whether the circle shape data can be revised to horizontal type by affine transformation. Please confirm it. Thanks so much..

**Comment by bharatsubedi** [comment]
> As I check some blogs describing for this FOTS, it seems the recgnition model to be similar as CRNN, so if the data is circle shape, it shoule be treated to horizontal shape during RoIRotate stage, is it right?

yes. If you want to use FOTS you have to make a circle characters ground truth also rectangular form.

**Comment by lmw0320** [comment]
Thanks, it means the GT for circle characters should be marked as below ？
![1](https://user-images.githubusercontent.com/37755235/97819626-bcc3c580-1ce4-11eb-9552-6faf72386293.png)
And, how the model infer this image，circle characters would be recgnized as one part , and the horizontal characters would be recgnized as the other?  
Because my project is to detect the images including this stamp also with horizontal together, I just want to understand this model.

**Comment by bharatsubedi** [comment]
<img width="208" alt="Capture" src="https://user-images.githubusercontent.com/14069935/97827569-07a30480-1d08-11eb-8d66-2f32ba00bb0c.PNG">
If you want to train your data using FOTs, create annotations like the above sample. At last, you can get string by sorting coordinate value. But I am not sure the FOTs network will work on your data or not. Otherwise, you can use some curve text detection and recognition techniques.

**Comment by lmw0320** [comment]
> <img alt="Capture" width="208" src="https://user-images.githubusercontent.com/14069935/97827569-07a30480-1d08-11eb-8d66-2f32ba00bb0c.PNG">
> 
> If you want to train your data using FOTs, create annotations like the above sample. At last, you can get string by sorting coordinate value. But I am not sure the FOTs network will work on your data or not. Otherwise, you can use some curve text detection and recognition techniques.

Noted, thanks for your kind advice.
